# Generated by Django 4.0.6 on 2022-10-20 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookname', models.CharField(default='未命名记忆本', max_length=512, primary_key=True, serialize=False)),
                ('pic', models.CharField(default='/static/default/bookPic.png', max_length=64)),
                ('tag', models.CharField(default='未分类', max_length=64)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('nickname', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('pic', models.CharField(default='/static/default/userPic.png', max_length=64)),
                ('days', models.IntegerField(default=0)),
                ('target', models.CharField(max_length=64)),
                ('level', models.IntegerField(default=0)),
                ('stuId', models.CharField(max_length=16)),
                ('institute', models.CharField(max_length=64)),
                ('major', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('msg', models.CharField(default='', max_length=1024)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to='user.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('ques', models.CharField(max_length=1024)),
                ('ans1', models.CharField(max_length=1024, null=True)),
                ('ans2', models.CharField(max_length=1024, null=True)),
                ('ans3', models.CharField(max_length=1024, null=True)),
                ('ans4', models.CharField(max_length=1024, null=True)),
                ('bookname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.book')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('favor', models.IntegerField(default=0)),
                ('title', models.CharField(default='Title', max_length=1024)),
                ('content', models.CharField(default='content', max_length=4096)),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='LearnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.book')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('nickname1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nickname1', to='user.user')),
                ('nickname2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nickname2', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(default='content', max_length=1024)),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.post')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('msg', models.CharField(default='', max_length=1024)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_receiver', to='user.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sender', to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
