# Generated by Django 4.0.6 on 2022-10-18 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
