# Generated by Django 4.0.6 on 2022-10-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(default='未命名记忆本', max_length=128, primary_key=True, serialize=False),
        ),
    ]
