# Generated by Django 4.0.6 on 2022-10-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_bookname_learnrecord_book_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnrecord',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='ques',
            old_name='book_id',
            new_name='book',
        ),
    ]
