# Generated by Django 4.0.6 on 2022-10-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_check_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
