# Generated by Django 4.0.6 on 2022-10-20 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_book_bookname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='nickname',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
