# Generated by Django 4.0.6 on 2022-10-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_grade_user_institute_user_level_user_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='institute',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='stuId',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='target',
            field=models.CharField(max_length=64),
        ),
    ]
