# Generated by Django 4.0.6 on 2022-12-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_book_id_learnrecord_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isLearning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='process',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.CharField(default='bookPic.png', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.CharField(default='userPic.png', max_length=64),
        ),
    ]
