# Generated by Django 4.0.6 on 2022-10-20 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_ques_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
