# Generated by Django 4.0.6 on 2022-10-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_ques_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnrecord',
            old_name='bookId',
            new_name='bookname',
        ),
    ]
