# Generated by Django 4.0.6 on 2022-12-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_book_islearning_book_process_alter_book_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='next_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ques',
            name='review',
            field=models.IntegerField(default=0, max_length=1024),
        ),
    ]
