# Generated by Django 4.0.6 on 2022-10-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_bookid_learnrecord_bookname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='未分类', max_length=32),
        ),
    ]
