# Generated by Django 4.0.6 on 2022-12-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_ques_next_time_ques_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='review',
            field=models.IntegerField(default=0),
        ),
    ]
