# Generated by Django 4.0.6 on 2022-10-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnrecord',
            old_name='bookname',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='ques',
            old_name='bookname',
            new_name='book_id',
        ),
    ]
