# Generated by Django 4.0.6 on 2022-12-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_ques_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='next_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
