# Generated by Django 4.0.6 on 2022-12-27 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_ques_next_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommends',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='ques',
            name='next_time',
            field=models.DateTimeField(default=datetime.datetime(1999, 1, 1, 0, 0)),
        ),
    ]
